/* 
 * log_ids.h
 *
 *  Generated on: {{date}}
 *      
 *  IDs for logging system
 *     This file is auto-generated by log_ids_h_gen.py from log IDs contained in log_ids.json
*/

// Turn off formatting so that the template doesn't get adjusted by the formatter.
// clang-format off

#ifndef LOG_ID_H_
#define LOG_ID_H_

/*
 * DO NOT MODIFY THIS FILE
 */

{% for entry in log_ids -%}
#define {{ entry }} {{ log_ids[entry]['id'] }} /* {{log_ids[entry]['description']}} */
{% endfor %}

/*
 * DO NOT MODIFY THIS FILE
 */

// clang-format on

#endif /* LOG_ID_H_ */
