/* 
 * log_ids.h
 *
 *  Generated on: {{date}}
 *      
 *  IDs for logging system
 *     This file is auto-generated by log_ids_h_gen.py from log IDs contained in log_ids.json
*/

// Turn off formatting so that the template doesn't get adjusted by the formatter.
// clang-format off

#ifndef LOG_ID_H_
#define LOG_ID_H_

/*
 * DO NOT MODIFY THIS FILE
 */

typedef enum {
{% for entry in log_ids %}
    {{ entry }} = {{ log_ids[entry]['id'] }}, /* {{log_ids[entry]['description']}} */
{% endfor %}
} log_id_t;

typedef enum {
{% for entry in log_ids %}
  /* {{ entry }} */
  {% for signal in log_ids[entry]['signals'] -%}
    {{entry}}__{{signal}} = {{ log_ids[entry]['signals'][signal]['id'] }}, /* "{{log_ids[entry]['signals'][signal]['description']}}" */
  {% endfor %}
{%- endfor %}
} signal_id_t;

/*
 * DO NOT MODIFY THIS FILE
 */

// clang-format on

#endif /* LOG_ID_H_ */
