# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panels.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlPanels(object):
    def setupUi(self, ControlPanels):
        ControlPanels.setObjectName("ControlPanels")
        ControlPanels.resize(801, 460)
        self.gridLayout = QtWidgets.QGridLayout(ControlPanels)
        self.gridLayout.setObjectName("gridLayout")
        self.control_tabs = QtWidgets.QTabWidget(ControlPanels)
        self.control_tabs.setObjectName("control_tabs")
        self.gridLayout.addWidget(self.control_tabs, 1, 0, 1, 1)

        self.retranslateUi(ControlPanels)
        QtCore.QMetaObject.connectSlotsByName(ControlPanels)

    def retranslateUi(self, ControlPanels):
        _translate = QtCore.QCoreApplication.translate
        ControlPanels.setWindowTitle(_translate("ControlPanels", "Form"))
