# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'san_antonio_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SanAntonioLog(object):
    def setupUi(self, SanAntonioLog):
        SanAntonioLog.setObjectName("SanAntonioLog")
        SanAntonioLog.resize(595, 171)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SanAntonioLog.sizePolicy().hasHeightForWidth())
        SanAntonioLog.setSizePolicy(sizePolicy)
        SanAntonioLog.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(SanAntonioLog)
        self.gridLayout.setObjectName("gridLayout")
        self.sa_log_box = QtWidgets.QGroupBox(SanAntonioLog)
        self.sa_log_box.setObjectName("sa_log_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.sa_log_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sa_log_text = QtWidgets.QTextEdit(self.sa_log_box)
        self.sa_log_text.setReadOnly(True)
        self.sa_log_text.setAcceptRichText(True)
        self.sa_log_text.setObjectName("sa_log_text")
        self.gridLayout_6.addWidget(self.sa_log_text, 0, 0, 1, 1)
        self.sa_log_clear_btn = QtWidgets.QPushButton(self.sa_log_box)
        self.sa_log_clear_btn.setObjectName("sa_log_clear_btn")
        self.gridLayout_6.addWidget(self.sa_log_clear_btn, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.sa_log_box, 0, 0, 1, 1)

        self.retranslateUi(SanAntonioLog)
        QtCore.QMetaObject.connectSlotsByName(SanAntonioLog)

    def retranslateUi(self, SanAntonioLog):
        _translate = QtCore.QCoreApplication.translate
        SanAntonioLog.setWindowTitle(_translate("SanAntonioLog", "Form"))
        self.sa_log_box.setTitle(_translate("SanAntonioLog", "San Antonio Log"))
        self.sa_log_clear_btn.setText(_translate("SanAntonioLog", "Clear Output"))
