# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sat_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SatInterface(object):
    def setupUi(self, SatInterface):
        SatInterface.setObjectName("SatInterface")
        SatInterface.resize(801, 132)
        self.gridLayout = QtWidgets.QGridLayout(SatInterface)
        self.gridLayout.setObjectName("gridLayout")
        self.sat_if_box = QtWidgets.QGroupBox(SatInterface)
        self.sat_if_box.setObjectName("sat_if_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sat_if_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comms_serial_if_btn = QtWidgets.QPushButton(self.sat_if_box)
        self.comms_serial_if_btn.setFlat(False)
        self.comms_serial_if_btn.setObjectName("comms_serial_if_btn")
        self.gridLayout_2.addWidget(self.comms_serial_if_btn, 0, 1, 1, 1)
        self.obc_serial_ports_cb = QtWidgets.QComboBox(self.sat_if_box)
        self.obc_serial_ports_cb.setObjectName("obc_serial_ports_cb")
        self.gridLayout_2.addWidget(self.obc_serial_ports_cb, 1, 0, 1, 1)
        self.obc_serial_if_btn = QtWidgets.QPushButton(self.sat_if_box)
        self.obc_serial_if_btn.setStyleSheet("")
        self.obc_serial_if_btn.setCheckable(False)
        self.obc_serial_if_btn.setFlat(False)
        self.obc_serial_if_btn.setObjectName("obc_serial_if_btn")
        self.gridLayout_2.addWidget(self.obc_serial_if_btn, 0, 0, 1, 1)
        self.comms_serial_ports_cb = QtWidgets.QComboBox(self.sat_if_box)
        self.comms_serial_ports_cb.setObjectName("comms_serial_ports_cb")
        self.gridLayout_2.addWidget(self.comms_serial_ports_cb, 1, 1, 1, 1)
        self.refresh_devices_btn = QtWidgets.QPushButton(self.sat_if_box)
        self.refresh_devices_btn.setObjectName("refresh_devices_btn")
        self.gridLayout_2.addWidget(self.refresh_devices_btn, 1, 3, 1, 1)
        self.connect_obc_serial_btn = QtWidgets.QPushButton(self.sat_if_box)
        self.connect_obc_serial_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_obc_serial_btn.sizePolicy().hasHeightForWidth())
        self.connect_obc_serial_btn.setSizePolicy(sizePolicy)
        self.connect_obc_serial_btn.setObjectName("connect_obc_serial_btn")
        self.gridLayout_2.addWidget(self.connect_obc_serial_btn, 2, 0, 1, 1)
        self.connect_comms_serial_btn = QtWidgets.QPushButton(self.sat_if_box)
        self.connect_comms_serial_btn.setObjectName("connect_comms_serial_btn")
        self.gridLayout_2.addWidget(self.connect_comms_serial_btn, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.sat_if_box, 0, 0, 1, 1)

        self.retranslateUi(SatInterface)
        QtCore.QMetaObject.connectSlotsByName(SatInterface)

    def retranslateUi(self, SatInterface):
        _translate = QtCore.QCoreApplication.translate
        SatInterface.setWindowTitle(_translate("SatInterface", "Form"))
        self.sat_if_box.setTitle(_translate("SatInterface", "Satellite Interface"))
        self.comms_serial_if_btn.setText(_translate("SatInterface", "COMMS Serial"))
        self.obc_serial_if_btn.setText(_translate("SatInterface", "OBC Serial"))
        self.refresh_devices_btn.setText(_translate("SatInterface", "Refresh Devices"))
        self.connect_obc_serial_btn.setText(_translate("SatInterface", "Connect"))
        self.connect_comms_serial_btn.setText(_translate("SatInterface", "Connect"))
