.build:
  stage: build
  image:
    name: registry.gitlab.com/alea-2020/command-data-handling/obc2-firmware/obc-fw-build-tools:1.1
    entrypoint: [""]
  before_script:
    - cd obc-firmware
  only:
    - merge_requests
    - web
  artifacts:
      when: always
      paths:
          - "obc-firmware/build/_bin/*.elf"
      expire_in: 1 month

.test:
  stage: test
  tags:
    - obc-alea-v1-runner
  before_script:
    - export DEVICE_PORT=/dev/ttyUSB0
    - cd hill-tests/obc_tests
  only:
    - merge_requests
    - web

build-launchpad:
  extends: .build
  script:
    - ./cmake_wrapper.sh launchpad

build-alea-v1:
  extends: .build
  script:
    - ./cmake_wrapper.sh alea-v1

test-alea-v1:
  extends: .test
  dependencies:
    - build-alea-v1
  script:
    - ../../obc-firmware/tools/infra/jlink-flash-alea-v1.sh -f ../../obc-firmware/build/_bin/*.elf
    - ./run-all-alea-v1.sh
