# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panels/tasks_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TasksPanel(object):
    def setupUi(self, TasksPanel):
        TasksPanel.setObjectName("TasksPanel")
        TasksPanel.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TasksPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_panel = QtWidgets.QWidget(TasksPanel)
        self.button_panel.setObjectName("button_panel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_panel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_stack_usage_btn = QtWidgets.QPushButton(self.button_panel)
        self.check_stack_usage_btn.setObjectName("check_stack_usage_btn")
        self.horizontalLayout.addWidget(self.check_stack_usage_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.button_panel)
        self.tasks_table = QtWidgets.QTableWidget(TasksPanel)
        self.tasks_table.setShowGrid(False)
        self.tasks_table.setObjectName("tasks_table")
        self.tasks_table.setColumnCount(0)
        self.tasks_table.setRowCount(0)
        self.tasks_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tasks_table)

        self.retranslateUi(TasksPanel)
        QtCore.QMetaObject.connectSlotsByName(TasksPanel)

    def retranslateUi(self, TasksPanel):
        _translate = QtCore.QCoreApplication.translate
        TasksPanel.setWindowTitle(_translate("TasksPanel", "Form"))
        self.check_stack_usage_btn.setText(_translate("TasksPanel", "Check Stack Usage"))
