# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panels/tasks_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TasksPanel(object):
    def setupUi(self, TasksPanel):
        TasksPanel.setObjectName("TasksPanel")
        TasksPanel.resize(738, 511)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(TasksPanel)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_panel = QtWidgets.QWidget(TasksPanel)
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_button_panel = QtWidgets.QWidget(self.left_panel)
        self.left_button_panel.setObjectName("left_button_panel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.left_button_panel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.check_stack_usage_btn = QtWidgets.QPushButton(self.left_button_panel)
        self.check_stack_usage_btn.setObjectName("check_stack_usage_btn")
        self.horizontalLayout.addWidget(self.check_stack_usage_btn)
        self.verticalLayout_2.addWidget(self.left_button_panel)
        self.tasks_table = QtWidgets.QTableWidget(self.left_panel)
        self.tasks_table.setShowGrid(False)
        self.tasks_table.setObjectName("tasks_table")
        self.tasks_table.setColumnCount(0)
        self.tasks_table.setRowCount(0)
        self.tasks_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tasks_table)
        self.horizontalLayout_2.addWidget(self.left_panel)
        self.right_panel = QtWidgets.QWidget(TasksPanel)
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.right_button_panel = QtWidgets.QWidget(self.right_panel)
        self.right_button_panel.setObjectName("right_button_panel")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.right_button_panel)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.trace_length_label = QtWidgets.QLabel(self.right_button_panel)
        self.trace_length_label.setObjectName("trace_length_label")
        self.horizontalLayout_3.addWidget(self.trace_length_label)
        self.trace_length_box = QtWidgets.QSpinBox(self.right_button_panel)
        self.trace_length_box.setMaximum(127)
        self.trace_length_box.setProperty("value", 127)
        self.trace_length_box.setDisplayIntegerBase(10)
        self.trace_length_box.setObjectName("trace_length_box")
        self.horizontalLayout_3.addWidget(self.trace_length_box)
        self.capture_task_trace_btn = QtWidgets.QPushButton(self.right_button_panel)
        self.capture_task_trace_btn.setObjectName("capture_task_trace_btn")
        self.horizontalLayout_3.addWidget(self.capture_task_trace_btn)
        self.verticalLayout.addWidget(self.right_button_panel)
        self.trace_table = QtWidgets.QTableWidget(self.right_panel)
        self.trace_table.setObjectName("trace_table")
        self.trace_table.setColumnCount(0)
        self.trace_table.setRowCount(0)
        self.verticalLayout.addWidget(self.trace_table)
        self.horizontalLayout_2.addWidget(self.right_panel)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 4)

        self.retranslateUi(TasksPanel)
        QtCore.QMetaObject.connectSlotsByName(TasksPanel)

    def retranslateUi(self, TasksPanel):
        _translate = QtCore.QCoreApplication.translate
        TasksPanel.setWindowTitle(_translate("TasksPanel", "Form"))
        self.check_stack_usage_btn.setText(_translate("TasksPanel", "Check Stack Usage"))
        self.trace_length_label.setText(_translate("TasksPanel", "# Context Switches:"))
        self.capture_task_trace_btn.setText(_translate("TasksPanel", "Capture Task Trace"))
