variables:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  PUPPETEER_SKIP_DOWNLOAD: "true"
  CYPRESS_INSTALL_BINARY: "0"
  GODEBUG: "http2client=0"
  HUSKY: "0"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  CACHE_COMPRESSION_FORMAT: "tarzstd"
