spec:
  inputs:
    package:
    environment:
    tag:
---
"Deploy $[[ inputs.package ]] to $[[ inputs.environment ]]":
  image: alpine:latest
  stage: deploy to $[[ inputs.environment ]]
  before_script:
    - apk add --no-cache yq openssh-client git curl
    - mkdir -p ~/.ssh
    - echo "$GITMOPSOPS_SSH_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - git config --global user.email "mops@ubcorbit.com"
    - git config --global user.name "MOps CI Bot"
    - git clone git@gitlab.com:alea-2020/mission-operations/gitmopsops.git
    - cd gitmopsops
    - git checkout master
  script:
    - cd $[[ inputs.environment ]]
    - yq e '.images |= map(select(.name == "registry.gitlab.com/alea-2020/mission-operations/barbours-cut/$[[ inputs.package ]]:latest") |= ( .newTag="$[[ inputs.tag | expand_vars ]]" | .newName="registry.gitlab.com/alea-2020/software/aleasat-software/$[[ inputs.package ]]"))' -i $[[ inputs.package ]]/kustomization.yaml
    - git add .
    - git commit -m "Update $[[ inputs.package ]] image version to $[[ inputs.tag | expand_vars ]]" || exit 0
    - git push
    - export CI_MERGE_REQUEST_IID="${CI_MERGE_REQUEST_IID:-$(echo $CI_COMMIT_TITLE | sed -E 's/.*\(!([0-9]+)\)$/\1/')}"
    - json_data='{"body":"Deployed `$[[ inputs.package ]]` to $[[ inputs.environment ]]. Please give a few minutes for the deployment to complete."}'
    - |
      echo $json_data |
      curl --request POST \
        --header "PRIVATE-TOKEN: ${DANGER_GITLAB_API_TOKEN}" \
        --header "Content-Type: application/json" \
        --data @- \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes"

  resource_group: gitmopsops
  environment: $[[ inputs.environment ]]/$[[ inputs.package ]]
