# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImagePanel(object):
    def setupUi(self, ImagePanel):
        ImagePanel.setObjectName("ImagePanel")
        ImagePanel.resize(451, 366)
        self.gridLayout = QtWidgets.QGridLayout(ImagePanel)
        self.gridLayout.setObjectName("gridLayout")
        self.clear_btn = QtWidgets.QPushButton(ImagePanel)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 2, 0, 1, 1)
        self.image_label = QtWidgets.QLabel(ImagePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setMinimumSize(QtCore.QSize(320, 0))
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 0, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(ImagePanel)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 1, 0, 1, 1)

        self.retranslateUi(ImagePanel)
        QtCore.QMetaObject.connectSlotsByName(ImagePanel)
        ImagePanel.setTabOrder(self.save_btn, self.clear_btn)

    def retranslateUi(self, ImagePanel):
        _translate = QtCore.QCoreApplication.translate
        ImagePanel.setWindowTitle(_translate("ImagePanel", "Form"))
        self.clear_btn.setText(_translate("ImagePanel", "Clear Image"))
        self.image_label.setText(_translate("ImagePanel", "No image"))
        self.save_btn.setText(_translate("ImagePanel", "Save Image..."))
