# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obc_cmd_resp_sched_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OBCCmdRespSchedPanel(object):
    def setupUi(self, OBCCmdRespSchedPanel):
        OBCCmdRespSchedPanel.setObjectName("OBCCmdRespSchedPanel")
        OBCCmdRespSchedPanel.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(OBCCmdRespSchedPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.obc_cmd_resp_sched_tree = QtWidgets.QTreeWidget(OBCCmdRespSchedPanel)
        self.obc_cmd_resp_sched_tree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.obc_cmd_resp_sched_tree.setWordWrap(True)
        self.obc_cmd_resp_sched_tree.setColumnCount(0)
        self.obc_cmd_resp_sched_tree.setObjectName("obc_cmd_resp_sched_tree")
        self.obc_cmd_resp_sched_tree.header().setStretchLastSection(False)
        self.gridLayout.addWidget(self.obc_cmd_resp_sched_tree, 0, 0, 1, 1)

        self.retranslateUi(OBCCmdRespSchedPanel)
        QtCore.QMetaObject.connectSlotsByName(OBCCmdRespSchedPanel)

    def retranslateUi(self, OBCCmdRespSchedPanel):
        _translate = QtCore.QCoreApplication.translate
        OBCCmdRespSchedPanel.setWindowTitle(_translate("OBCCmdRespSchedPanel", "Form"))
