# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obc_serial_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OBCSerialLog(object):
    def setupUi(self, OBCSerialLog):
        OBCSerialLog.setObjectName("OBCSerialLog")
        OBCSerialLog.resize(516, 174)
        self.gridLayout = QtWidgets.QGridLayout(OBCSerialLog)
        self.gridLayout.setObjectName("gridLayout")
        self.obc_log_box = QtWidgets.QGroupBox(OBCSerialLog)
        self.obc_log_box.setObjectName("obc_log_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.obc_log_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.obc_log_table = QtWidgets.QTableWidget(self.obc_log_box)
        self.obc_log_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.obc_log_table.setColumnCount(0)
        self.obc_log_table.setObjectName("obc_log_table")
        self.obc_log_table.setRowCount(0)
        self.obc_log_table.horizontalHeader().setCascadingSectionResizes(False)
        self.obc_log_table.horizontalHeader().setDefaultSectionSize(150)
        self.obc_log_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.obc_log_table, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.obc_log_box, 0, 0, 1, 1)

        self.retranslateUi(OBCSerialLog)
        QtCore.QMetaObject.connectSlotsByName(OBCSerialLog)

    def retranslateUi(self, OBCSerialLog):
        _translate = QtCore.QCoreApplication.translate
        OBCSerialLog.setWindowTitle(_translate("OBCSerialLog", "Form"))
        self.obc_log_box.setTitle(_translate("OBCSerialLog", "OBC Serial Log"))
