# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obc_serial_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OBCSerialLog(object):
    def setupUi(self, OBCSerialLog):
        OBCSerialLog.setObjectName("OBCSerialLog")
        OBCSerialLog.resize(516, 182)
        self.gridLayout = QtWidgets.QGridLayout(OBCSerialLog)
        self.gridLayout.setObjectName("gridLayout")
        self.obc_log_box = QtWidgets.QGroupBox(OBCSerialLog)
        self.obc_log_box.setObjectName("obc_log_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.obc_log_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.obc_log_table = QtWidgets.QTableWidget(self.obc_log_box)
        self.obc_log_table.setMinimumSize(QtCore.QSize(0, 100))
        self.obc_log_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.obc_log_table.setColumnCount(0)
        self.obc_log_table.setObjectName("obc_log_table")
        self.obc_log_table.setRowCount(0)
        self.obc_log_table.horizontalHeader().setCascadingSectionResizes(False)
        self.obc_log_table.horizontalHeader().setDefaultSectionSize(150)
        self.obc_log_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.obc_log_table, 0, 0, 1, 1)
        self.buttonLayout = QtWidgets.QGridLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.obc_log_save_btn = QtWidgets.QPushButton(self.obc_log_box)
        self.obc_log_save_btn.setObjectName("obc_log_save_btn")
        self.buttonLayout.addWidget(self.obc_log_save_btn, 0, 1, 1, 1)
        self.obc_log_clear_btn = QtWidgets.QPushButton(self.obc_log_box)
        self.obc_log_clear_btn.setObjectName("obc_log_clear_btn")
        self.buttonLayout.addWidget(self.obc_log_clear_btn, 0, 2, 1, 1)
        self.watchdog_checkbox = QtWidgets.QCheckBox(self.obc_log_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.watchdog_checkbox.sizePolicy().hasHeightForWidth())
        self.watchdog_checkbox.setSizePolicy(sizePolicy)
        self.watchdog_checkbox.setObjectName("watchdog_checkbox")
        self.buttonLayout.addWidget(self.watchdog_checkbox, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.buttonLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.obc_log_box, 0, 0, 1, 1)

        self.retranslateUi(OBCSerialLog)
        QtCore.QMetaObject.connectSlotsByName(OBCSerialLog)

    def retranslateUi(self, OBCSerialLog):
        _translate = QtCore.QCoreApplication.translate
        OBCSerialLog.setWindowTitle(_translate("OBCSerialLog", "Form"))
        self.obc_log_box.setTitle(_translate("OBCSerialLog", "OBC Serial Log"))
        self.obc_log_save_btn.setText(_translate("OBCSerialLog", "Save"))
        self.obc_log_clear_btn.setText(_translate("OBCSerialLog", "Clear"))
        self.watchdog_checkbox.setText(_translate("OBCSerialLog", "Watchdog Messages"))
