# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obc_cmd_resp_imm_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OBCCmdRespImmPanel(object):
    def setupUi(self, OBCCmdRespImmPanel):
        OBCCmdRespImmPanel.setObjectName("OBCCmdRespImmPanel")
        OBCCmdRespImmPanel.resize(299, 298)
        self.gridLayout = QtWidgets.QGridLayout(OBCCmdRespImmPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.obc_cmd_resp_imm_table = QtWidgets.QTableWidget(OBCCmdRespImmPanel)
        self.obc_cmd_resp_imm_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.obc_cmd_resp_imm_table.setObjectName("obc_cmd_resp_imm_table")
        self.obc_cmd_resp_imm_table.setColumnCount(0)
        self.obc_cmd_resp_imm_table.setRowCount(0)
        self.obc_cmd_resp_imm_table.horizontalHeader().setStretchLastSection(False)
        self.obc_cmd_resp_imm_table.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.obc_cmd_resp_imm_table, 0, 0, 1, 1)
        self.buttonLayout = QtWidgets.QGridLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.obc_cmd_resp_save_btn = QtWidgets.QPushButton(OBCCmdRespImmPanel)
        self.obc_cmd_resp_save_btn.setObjectName("obc_cmd_resp_save_btn")
        self.buttonLayout.addWidget(self.obc_cmd_resp_save_btn, 0, 0, 1, 1)
        self.obc_cmd_resp_clear_btn = QtWidgets.QPushButton(OBCCmdRespImmPanel)
        self.obc_cmd_resp_clear_btn.setObjectName("obc_cmd_resp_clear_btn")
        self.buttonLayout.addWidget(self.obc_cmd_resp_clear_btn, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.buttonLayout, 1, 0, 1, 1)

        self.retranslateUi(OBCCmdRespImmPanel)
        QtCore.QMetaObject.connectSlotsByName(OBCCmdRespImmPanel)

    def retranslateUi(self, OBCCmdRespImmPanel):
        _translate = QtCore.QCoreApplication.translate
        OBCCmdRespImmPanel.setWindowTitle(_translate("OBCCmdRespImmPanel", "Form"))
        self.obc_cmd_resp_save_btn.setText(_translate("OBCCmdRespImmPanel", "Save"))
        self.obc_cmd_resp_clear_btn.setText(_translate("OBCCmdRespImmPanel", "Clear"))
