# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obc_cmd_resp_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OBCCmdRespPanel(object):
    def setupUi(self, OBCCmdRespPanel):
        OBCCmdRespPanel.setObjectName("OBCCmdRespPanel")
        OBCCmdRespPanel.resize(818, 670)
        self.gridLayout = QtWidgets.QGridLayout(OBCCmdRespPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.obc_cmd_resp_box = QtWidgets.QGroupBox(OBCCmdRespPanel)
        self.obc_cmd_resp_box.setMinimumSize(QtCore.QSize(800, 0))
        self.obc_cmd_resp_box.setObjectName("obc_cmd_resp_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.obc_cmd_resp_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.obc_cmd_resp_tabs = QtWidgets.QTabWidget(self.obc_cmd_resp_box)
        self.obc_cmd_resp_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.obc_cmd_resp_tabs.setDocumentMode(False)
        self.obc_cmd_resp_tabs.setObjectName("obc_cmd_resp_tabs")
        self.gridLayout_2.addWidget(self.obc_cmd_resp_tabs, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.obc_cmd_resp_box, 0, 0, 1, 1)

        self.retranslateUi(OBCCmdRespPanel)
        self.obc_cmd_resp_tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(OBCCmdRespPanel)

    def retranslateUi(self, OBCCmdRespPanel):
        _translate = QtCore.QCoreApplication.translate
        OBCCmdRespPanel.setWindowTitle(_translate("OBCCmdRespPanel", "Form"))
        self.obc_cmd_resp_box.setTitle(_translate("OBCCmdRespPanel", "OBC Commands / Responses"))
