# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sat_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SatInterface(object):
    def setupUi(self, SatInterface):
        SatInterface.setObjectName("SatInterface")
        SatInterface.resize(805, 130)
        self.gridLayout = QtWidgets.QGridLayout(SatInterface)
        self.gridLayout.setObjectName("gridLayout")
        self.sat_if_box = QtWidgets.QGroupBox(SatInterface)
        self.sat_if_box.setObjectName("sat_if_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sat_if_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.obc_serial_connect_btn = QtWidgets.QPushButton(self.sat_if_box)
        self.obc_serial_connect_btn.setObjectName("obc_serial_connect_btn")
        self.gridLayout_3.addWidget(self.obc_serial_connect_btn, 2, 1, 1, 1)
        self.obc_serial_ports_cb = QtWidgets.QComboBox(self.sat_if_box)
        self.obc_serial_ports_cb.setObjectName("obc_serial_ports_cb")
        self.gridLayout_3.addWidget(self.obc_serial_ports_cb, 2, 0, 1, 1)
        self.obc_serial_label = QtWidgets.QLabel(self.sat_if_box)
        self.obc_serial_label.setObjectName("obc_serial_label")
        self.gridLayout_3.addWidget(self.obc_serial_label, 0, 0, 1, 1)
        self.obc_serial_status_label = QtWidgets.QLabel(self.sat_if_box)
        self.obc_serial_status_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.obc_serial_status_label.setObjectName("obc_serial_status_label")
        self.gridLayout_3.addWidget(self.obc_serial_status_label, 0, 1, 1, 1)
        self.obc_serial_refresh_btn = QtWidgets.QPushButton(self.sat_if_box)
        self.obc_serial_refresh_btn.setObjectName("obc_serial_refresh_btn")
        self.gridLayout_3.addWidget(self.obc_serial_refresh_btn, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.sat_if_box, 1, 0, 1, 1)

        self.retranslateUi(SatInterface)
        QtCore.QMetaObject.connectSlotsByName(SatInterface)

    def retranslateUi(self, SatInterface):
        _translate = QtCore.QCoreApplication.translate
        SatInterface.setWindowTitle(_translate("SatInterface", "Form"))
        self.sat_if_box.setTitle(_translate("SatInterface", "Satellite Interface"))
        self.obc_serial_connect_btn.setText(_translate("SatInterface", "Connect"))
        self.obc_serial_label.setText(_translate("SatInterface", "OBC Serial:"))
        self.obc_serial_status_label.setText(_translate("SatInterface", "DISCONNECTED"))
        self.obc_serial_refresh_btn.setText(_translate("SatInterface", "Refresh Ports"))
